name: Verificar estado de fabricantes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'  # Todos los días a las 9:00 UTC

jobs:
  ejecutar-monitor:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Instalar Chromium y Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver || true

      - name: Ejecutar script principal
        run: python main.py
