name: Status Monitor - Netskope

on:
  schedule:
    - cron: '*/30 * * * *'  # Cada 30 min
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          sudo cp /usr/lib/chromium-browser/chromedriver /usr/bin

      - name: Ejecutar script principal
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: python main.py
