name: Web Status Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Ejecutar cada hora

jobs:
  check_status:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_USER_ID:   ${{ secrets.TELEGRAM_USER_ID }}
      TEAMS_WEBHOOK_URL:  ${{ secrets.TEAMS_WEBHOOK_URL }}
      # Activa guardado HTML si quieres depurar selectores:
      # SAVE_HTML: "1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Instala Google Chrome estable y exporta CHROME_PATH
      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Show Chrome version
        run: |
          echo "CHROME_PATH=$CHROME_PATH"
          "$CHROME_PATH" --version || true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitor
        run: python main.py
