name: Web Status Monitor (multi)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  monitor:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vendor: [netskope]  # agrega más: [netskope, zscaler, paloalto]
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_USER_ID:   ${{ secrets.TELEGRAM_USER_ID }}
      TEAMS_WEBHOOK_URL:  ${{ secrets.TEAMS_WEBHOOK_URL }}
      # SAVE_HTML: "1"  # si quieres depurar

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ${{ matrix.vendor }}
        run: python run_vendor.py --vendor ${{ matrix.vendor }}
