name: Web Status Monitor (multi)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # cada hora

jobs:
  monitor:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        vendor: [netskope, proofpoint, qualys, aruba]

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_USER_ID:   ${{ secrets.TELEGRAM_USER_ID }}
      TEAMS_WEBHOOK_URL:  ${{ secrets.TEAMS_WEBHOOK_URL }}
      SAVE_HTML: "1"  # <-- activa guardado de HTML para depurar

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ${{ matrix.vendor }}
        run: python run_vendor.py --vendor ${{ matrix.vendor }}

      - name: Upload page HTML (${{ matrix.vendor }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-${{ matrix.vendor }}
          path: |
            *page_source.html
            **/*page_source.html
          if-no-files-found: warn
          retention-days: 7
